@startuml

class Meal {
    - id: Long
    - name: String
    - shortDescription: String
    - imageUrl: String
    - recipes: List<Recipe>

}

class Recipe {
    - id: Long
    - title: String
    - ingredients: List<Ingredient>
    - customIngredients: List<CustomIngredient>
    - steps: List<String>
    - preparationTime: String
    - difficulty: DifficultyType
}


class Ingredient {
    - id: Long
    - food: Food
    - amount: Double
    - unit: MeasurementUnit
    - customLabel: String
}


class CustomIngredient {
    - name: String
    - amount: Double
    - unit: MeasurementUnit
    - note: String
}


class Food {
    - id: Long
    - name: String
    - nutritionalInfo: NutritionalInfo
    - micronutrients: List<MicronutrientContent>
    - measurementUnits: List<MeasurementUnit>
    - foodOrigin: FoodOriginType
    - nutritionalFunctions: List<NutritionalFunctionType>
}


class NutritionalInfo {
    - calories: Double
    - carbohydrates: Double
    - sugars: Double
    - proteins: Double
    - totalFats: Double
    - saturatedFats: Double
    - fiber: Double
}

class MicronutrientContent {
    - micronutrient: Micronutrient
    - amountPerGram: Double
}

class Micronutrient {
    - id: Long
    - name: String
    - dailyAmount: Double
    - unit: UnitType
}

class MeasurementUnit {
    - id: Long
    - unit: UnitType
    - gramsPerUnit: Double
}


Ingredient "1" *-- "1" Food
Ingredient "1" o-- "1" MeasurementUnit

Recipe "1" *-- "*" Ingredient

Food "1" *-- "1" NutritionalInfo
Food "1" *-- "*" MeasurementUnit
Food "1" *-- "*" MicronutrientContent

MicronutrientContent "1" *-- "1" Micronutrient



enum UnitType {
    GRAMS
    MILLIGRAMS
    KILOGRAMS
    MICROGRAMS
    MILLILITERS
    UNIT
    TABLESPOON
    TEASPOON
    PERCENTAGE
    AS_NEEDED
    TO_TASTE
    SLICE
    PIECE
    PINCH
    HANDFUL
    DASH
    DROP
}

enum FoodOriginType {
    GRAIN
    VEGETABLE
    FRUIT
    DAIRY
    PROTEIN
}

enum NutritionalFunctionType {
    ENERGY_FOOD
    REGULATORY_FOOD
    BUILDER_FOOD
}

enum DifficultyType {
    EASY
    INTERMEDIATE
    HARD
}

@enduml
